/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AnonymousConfessionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confessions"
      | "confidentialProtocolId"
      | "getConfessionCount"
      | "getConfessionTimestamp"
      | "storeConfession"
      | "verifyMyConfession"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ConfessionStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "confessions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfessionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfessionTimestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeConfession",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMyConfession",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfessionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfessionTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeConfession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMyConfession",
    data: BytesLike
  ): Result;
}

export namespace ConfessionStoredEvent {
  export type InputTuple = [
    confessionId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [confessionId: bigint, timestamp: bigint];
  export interface OutputObject {
    confessionId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnonymousConfessions extends BaseContract {
  connect(runner?: ContractRunner | null): AnonymousConfessions;
  waitForDeployment(): Promise<this>;

  interface: AnonymousConfessionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confessions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        message: string;
        authorHash: string;
        timestamp: bigint;
        confessionId: bigint;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getConfessionCount: TypedContractMethod<[], [bigint], "view">;

  getConfessionTimestamp: TypedContractMethod<
    [_confessionId: BigNumberish],
    [bigint],
    "view"
  >;

  storeConfession: TypedContractMethod<
    [encryptedMessage: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  verifyMyConfession: TypedContractMethod<
    [_confessionId: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confessions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        message: string;
        authorHash: string;
        timestamp: bigint;
        confessionId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getConfessionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getConfessionTimestamp"
  ): TypedContractMethod<[_confessionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "storeConfession"
  ): TypedContractMethod<
    [encryptedMessage: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyMyConfession"
  ): TypedContractMethod<[_confessionId: BigNumberish], [string], "nonpayable">;

  getEvent(
    key: "ConfessionStored"
  ): TypedContractEvent<
    ConfessionStoredEvent.InputTuple,
    ConfessionStoredEvent.OutputTuple,
    ConfessionStoredEvent.OutputObject
  >;

  filters: {
    "ConfessionStored(uint256,uint256)": TypedContractEvent<
      ConfessionStoredEvent.InputTuple,
      ConfessionStoredEvent.OutputTuple,
      ConfessionStoredEvent.OutputObject
    >;
    ConfessionStored: TypedContractEvent<
      ConfessionStoredEvent.InputTuple,
      ConfessionStoredEvent.OutputTuple,
      ConfessionStoredEvent.OutputObject
    >;
  };
}
