/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfessionsContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confessions"
      | "getConfession"
      | "getConfessionCount"
      | "getUserConfessions"
      | "submitConfession"
      | "userConfessions"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ConfessionSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "confessions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfessionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConfessions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitConfession",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userConfessions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfessionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConfessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitConfession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userConfessions",
    data: BytesLike
  ): Result;
}

export namespace ConfessionSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    hash: BytesLike,
    sentiment: BigNumberish,
    submitter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    hash: string,
    sentiment: bigint,
    submitter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    hash: string;
    sentiment: bigint;
    submitter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfessionsContract extends BaseContract {
  connect(runner?: ContractRunner | null): ConfessionsContract;
  waitForDeployment(): Promise<this>;

  interface: ConfessionsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confessions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        hash: string;
        sentiment: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getConfession: TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        hash: string;
        sentiment: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  getConfessionCount: TypedContractMethod<[], [bigint], "view">;

  getUserConfessions: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  submitConfession: TypedContractMethod<
    [_hash: BytesLike, _sentiment: BigNumberish],
    [void],
    "nonpayable"
  >;

  userConfessions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confessions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        hash: string;
        sentiment: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfession"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        hash: string;
        sentiment: bigint;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfessionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserConfessions"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "submitConfession"
  ): TypedContractMethod<
    [_hash: BytesLike, _sentiment: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userConfessions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ConfessionSubmitted"
  ): TypedContractEvent<
    ConfessionSubmittedEvent.InputTuple,
    ConfessionSubmittedEvent.OutputTuple,
    ConfessionSubmittedEvent.OutputObject
  >;

  filters: {
    "ConfessionSubmitted(uint256,bytes32,uint256,address,uint256)": TypedContractEvent<
      ConfessionSubmittedEvent.InputTuple,
      ConfessionSubmittedEvent.OutputTuple,
      ConfessionSubmittedEvent.OutputObject
    >;
    ConfessionSubmitted: TypedContractEvent<
      ConfessionSubmittedEvent.InputTuple,
      ConfessionSubmittedEvent.OutputTuple,
      ConfessionSubmittedEvent.OutputObject
    >;
  };
}
