/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEConfessionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confessionAuthors"
      | "confessions"
      | "decryptionCallback"
      | "getConfession"
      | "getConfessionCount"
      | "getUserConfessions"
      | "requestDecryption"
      | "submitConfession"
      | "verifyOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfessionSubmitted"
      | "DecryptionCompleted"
      | "DecryptionRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confessionAuthors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confessions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionCallback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfessionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConfessions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitConfession",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyOwnership",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confessionAuthors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfessionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConfessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitConfession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConfessionSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    authorCommitment: BytesLike,
    timestamp: BigNumberish,
    sentiment: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    authorCommitment: string,
    timestamp: bigint,
    sentiment: bigint
  ];
  export interface OutputObject {
    id: bigint;
    authorCommitment: string;
    timestamp: bigint;
    sentiment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionCompletedEvent {
  export type InputTuple = [confessionId: BigNumberish, decryptedText: string];
  export type OutputTuple = [confessionId: bigint, decryptedText: string];
  export interface OutputObject {
    confessionId: bigint;
    decryptedText: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [
    confessionId: BigNumberish,
    requestId: BigNumberish
  ];
  export type OutputTuple = [confessionId: bigint, requestId: bigint];
  export interface OutputObject {
    confessionId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEConfessions extends BaseContract {
  connect(runner?: ContractRunner | null): FHEConfessions;
  waitForDeployment(): Promise<this>;

  interface: FHEConfessionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confessionAuthors: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  confessions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, boolean, string] & {
        id: bigint;
        encryptedMessage: bigint;
        authorCommitment: string;
        timestamp: bigint;
        sentiment: bigint;
        isDecrypted: boolean;
        decryptedText: string;
      }
    ],
    "view"
  >;

  decryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, decryptedValue: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getConfession: TypedContractMethod<
    [confessionId: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, string] & {
        id: bigint;
        authorCommitment: string;
        timestamp: bigint;
        sentiment: bigint;
        isDecrypted: boolean;
        decryptedText: string;
      }
    ],
    "view"
  >;

  getConfessionCount: TypedContractMethod<[], [bigint], "view">;

  getUserConfessions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  requestDecryption: TypedContractMethod<
    [confessionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitConfession: TypedContractMethod<
    [
      _encryptedMessage: BytesLike,
      inputProof: BytesLike,
      _authorCommitment: BytesLike,
      _sentiment: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  verifyOwnership: TypedContractMethod<
    [confessionId: BigNumberish, nonce: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confessionAuthors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "confessions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, boolean, string] & {
        id: bigint;
        encryptedMessage: bigint;
        authorCommitment: string;
        timestamp: bigint;
        sentiment: bigint;
        isDecrypted: boolean;
        decryptedText: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, decryptedValue: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getConfession"
  ): TypedContractMethod<
    [confessionId: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, string] & {
        id: bigint;
        authorCommitment: string;
        timestamp: bigint;
        sentiment: bigint;
        isDecrypted: boolean;
        decryptedText: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfessionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserConfessions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[confessionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitConfession"
  ): TypedContractMethod<
    [
      _encryptedMessage: BytesLike,
      inputProof: BytesLike,
      _authorCommitment: BytesLike,
      _sentiment: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyOwnership"
  ): TypedContractMethod<
    [confessionId: BigNumberish, nonce: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ConfessionSubmitted"
  ): TypedContractEvent<
    ConfessionSubmittedEvent.InputTuple,
    ConfessionSubmittedEvent.OutputTuple,
    ConfessionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionCompleted"
  ): TypedContractEvent<
    DecryptionCompletedEvent.InputTuple,
    DecryptionCompletedEvent.OutputTuple,
    DecryptionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;

  filters: {
    "ConfessionSubmitted(uint256,bytes32,uint256,uint256)": TypedContractEvent<
      ConfessionSubmittedEvent.InputTuple,
      ConfessionSubmittedEvent.OutputTuple,
      ConfessionSubmittedEvent.OutputObject
    >;
    ConfessionSubmitted: TypedContractEvent<
      ConfessionSubmittedEvent.InputTuple,
      ConfessionSubmittedEvent.OutputTuple,
      ConfessionSubmittedEvent.OutputObject
    >;

    "DecryptionCompleted(uint256,string)": TypedContractEvent<
      DecryptionCompletedEvent.InputTuple,
      DecryptionCompletedEvent.OutputTuple,
      DecryptionCompletedEvent.OutputObject
    >;
    DecryptionCompleted: TypedContractEvent<
      DecryptionCompletedEvent.InputTuple,
      DecryptionCompletedEvent.OutputTuple,
      DecryptionCompletedEvent.OutputObject
    >;

    "DecryptionRequested(uint256,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
  };
}
